version: '3.9'
services:
  usermanagementmsc:
    container_name: usermanagementmsc
    image: myusermanagementms
    environment:
      - LICIOT_DATABASE_HOST=192.168.5.100
      - LICIOT_KAFKA_BOOTSTRAP_SERVERS=192.168.5.19:19092
       
    networks:
      liciot_network:
         ipv4_address: "192.168.5.150"
    ports:
      - 9090:9090

  humanmicroservicec:
    container_name: humanmicroservicec
    image: myhumanmicroservice
    environment:
      - LICIOT_KAFKA_BOOTSTRAP_SERVERS=192.168.5.19:19092
      - LICIOT_USERMANAGEMENTMICROSERVICE_HOST=http://192.168.5.150:9090
    networks:
      liciot_network:
         ipv4_address: "192.168.5.151"
    ports:
      - 9091:9091
    
  devicemicroservicec:
    container_name: devicemicroservicec
    image: mydevicemicroservice
    environment:
      - LICIOT_KAFKA_BOOTSTRAP_SERVERS=192.168.5.19:19092
      - LICIOT_USERMANAGEMENTMICROSERVICE_HOST=http://192.168.5.150:9090
    networks:
      liciot_network:
         ipv4_address: "192.168.5.152"
    ports:
      - 9092:9092
   
networks:
  liciot_network:
    name: liciot_network
    external: true
