version: '3.9'
services:
  kafka_1c:
    container_name: kafka_1c
    image: mykafka
    networks:
      liciot_network:
         ipv4_address: "192.168.5.19"
  
    volumes:
      - ${KAFKACL_PATH}/kafka/myimagesdestination/kafka/volumes/kafka_1/config/server.properties:/kafka/config/server.properties
      - ${KAFKACL_PATH}/kafka/permanentvolumes/kafka/kafka_1/kafka-logs:/tmp/kafka-logs

  
networks:
  liciot_network:
    name: liciot_network
    external: true
