
database.ip       = ${DB_IP:localhost}
database.port     = ${DB_PORT:5432}
database.user     = ${DB_USER:multhingverse}
database.password = ${DB_PASSWORD:changeme}
database.name     = ${DB_DBNAME:multhingverse_db}

spring.datasource.platform = postgres
spring.datasource.url      = jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username = ${database.user}
spring.datasource.password = ${database.password}

spring.jpa.properties.hibernate.dialect  = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto            = update
spring.jpa.open-in-view                  = false
spring.jpa.properties.hibernate.show_sql = false

server.tomcat.threads.max = 25
server.port               = ${PORT:9091}

spring.servlet.multipart.enabled             = true
spring.servlet.multipart.file-size-threshold = 2KB
spring.servlet.multipart.max-file-size       = 200MB
spring.servlet.multipart.max-request-size    = 215MB

file.upload-dir = ${FILE_UPLOAD_DIR:/app/uploads/}

jwt.secret = ${JWT_SECRET:changeme}

server.forward-headers-strategy = native
