
database.ip       = ${DB_IP:localhost}
database.port     = ${DB_PORT:5432}
database.user     = ${SPRING_DATASOURCE_USERNAME:${DB_USER:multhingverse}}
database.password = ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:changeme}}
database.name     = ${DB_DBNAME:multhingverse_db}

spring.datasource.platform = postgres
spring.datasource.url      = jdbc:postgresql://${LICIOT_DATABASE_HOST:localhost}:${LICIOT_DATABASE_PORT:5432}/${LICIOT_DATABASE_NAME:${DB_DBNAME:multhingverse_db}}
spring.datasource.username = ${database.user}
spring.datasource.password = ${database.password}

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto           = update
spring.jpa.open-in-view                 = false
spring.jpa.properties.hibernate.show_sql = false

server.tomcat.threads.max = 100
server.port               = ${PORT:9090}

spring.servlet.multipart.enabled            = true
spring.servlet.multipart.file-size-threshold = 2KB
spring.servlet.multipart.max-file-size       = 200MB
spring.servlet.multipart.max-request-size    = 215MB

file.upload-dir = ${FILE_UPLOAD_DIR:/app/uploads/}

jwt.secret = ${JWT_SECRET:changeme}

google.oauth2.client-id     = ${GOOGLE_CLIENT_ID}
google.oauth2.client-secret = ${GOOGLE_CLIENT_SECRET}

server.forward-headers-strategy = native
